export const IconOptions = [
    { value: 'grocery', label: 'Grocery', icon: 'grocery' },
    { value: 'nutrition', label: 'Nutrition', icon: 'nutrition' },
    { value: 'person', label: 'Person', icon: 'person' },
    { value: 'local_shipping', label: 'Local Shipping', icon: 'local_shipping' },
    { value: 'home', label: 'Home', icon: 'home' },
    { value: 'music_note', label: 'Music Note', icon: 'music_note' },
    { value: 'book', label: 'Book', icon: 'book' },
    { value: 'camera', label: 'Camera', icon: 'camera' },
    { value: 'globe', label: 'Globe', icon: 'globe' },
    { value: 'favorite', label: 'Favorite', icon: 'favorite' },
    { value: 'star', label: 'Star', icon: 'star' },
    { value: 'smart_toy', label: 'Smart Toy', icon: 'smart_toy' },
    { value: 'movie', label: 'Movie', icon: 'movie' },
    { value: 'phone', label: 'Phone', icon: 'phone' },
    { value: 'mail', label: 'Mail', icon: 'mail' },
    { value: 'clock', label: 'Clock', icon: 'schedule' },
    { value: 'money', label: 'Money', icon: 'money' },
    { value: 'egg_alt', label: 'Egg Alt', icon: 'egg_alt' },
    { value: 'restaurant', label: 'Restaurant', icon: 'restaurant' },
    { value: 'computer', label: 'Computer', icon: 'computer' }
];

export const CountryOptions = [
    { value: 'us', label: 'United States', subTitle: 'US' },
    { value: 'ca', label: 'Canada', subTitle: 'CA' },
    { value: 'mx', label: 'Mexico', subTitle: 'MX' },
    { value: 'uk', label: 'United Kingdom', subTitle: 'UK' },
    { value: 'de', label: 'Germany', subTitle: 'DE' },
    { value: 'fr', label: 'France', subTitle: 'FR' },
    { value: 'es', label: 'Spain', subTitle: 'ES' },
    { value: 'it', label: 'Italy', subTitle: 'IT' },
    { value: 'jp', label: 'Japan', subTitle: 'JP' },
    { value: 'cn', label: 'China', subTitle: 'CN' },
    { value: 'au', label: 'Australia', subTitle: 'AU' },
    { value: 'br', label: 'Brazil', subTitle: 'BR' },
    { value: 'in', label: 'India', subTitle: 'IN' },
    { value: 'ru', label: 'Russia', subTitle: 'RU' },
    { value: 'sa', label: 'Saudi Arabia', subTitle: 'SA' },
    { value: 'za', label: 'South Africa', subTitle: 'ZA' },
    { value: 'eg', label: 'Egypt', subTitle: 'EG' },
    { value: 'ng', label: 'Nigeria', subTitle: 'NG' },
    { value: 'id', label: 'Indonesia', subTitle: 'ID' },
    { value: 'tr', label: 'Turkey', subTitle: 'TR' },
    { value: 'kr', label: 'South Korea', subTitle: 'KR' },
    { value: 'ar', label: 'Argentina', subTitle: 'AR' },
    { value: 'at', label: 'Austria', subTitle: 'AT' },
    { value: 'be', label: 'Belgium', subTitle: 'BE' },
    { value: 'ch', label: 'Switzerland', subTitle: 'CH' },
    { value: 'dk', label: 'Denmark', subTitle: 'DK' },
    { value: 'fi', label: 'Finland', subTitle: 'FI' },
    { value: 'gr', label: 'Greece', subTitle: 'GR' },
    { value: 'hk', label: 'Hong Kong', subTitle: 'HK' },
    { value: 'ie', label: 'Ireland', subTitle: 'IE' },
    { value: 'il', label: 'Israel', subTitle: 'IL' },
    { value: 'my', label: 'Malaysia', subTitle: 'MY' },
    { value: 'nl', label: 'Netherlands', subTitle: 'NL' },
    { value: 'no', label: 'Norway', subTitle: 'NO' },
    { value: 'pl', label: 'Poland', subTitle: 'PL' },
    { value: 'pt', label: 'Portugal', subTitle: 'PT' },
    { value: 'se', label: 'Sweden', subTitle: 'SE' },
    { value: 'sg', label: 'Singapore', subTitle: 'SG' },
    { value: 'th', label: 'Thailand', subTitle: 'TH' },
    { value: 'tw', label: 'Taiwan', subTitle: 'TW' },
    { value: 'vn', label: 'Vietnam', subTitle: 'VN' }
];
