/**
 * @typedef {import("../fields/optionsField/fieldOption/fieldOptionInterface").FieldOptionInterface} FieldOptionInterface
 */
export const IconOptions = [
    { value: 'grocery', label: 'Grocery', icon: 'grocery' },
    { value: 'nutrition', label: 'Nutrition', icon: 'nutrition' },
    { value: 'person', label: 'Person', icon: 'person' },
    { value: 'local_shipping', label: 'Local Shipping', icon: 'local_shipping' },
    { value: 'home', label: 'Home', icon: 'home' },
    { value: 'music_note', label: 'Music Note', icon: 'music_note' },
    { value: 'book', label: 'Book', icon: 'book' },
    { value: 'camera', label: 'Camera', icon: 'camera' },
    { value: 'globe', label: 'Globe', icon: 'globe' },
    { value: 'favorite', label: 'Favorite', icon: 'favorite' },
    { value: 'star', label: 'Star', icon: 'star' },
    { value: 'smart_toy', label: 'Smart Toy', icon: 'smart_toy' },
    { value: 'movie', label: 'Movie', icon: 'movie' },
    { value: 'phone', label: 'Phone', icon: 'phone' },
    { value: 'mail', label: 'Mail', icon: 'mail' },
    { value: 'clock', label: 'Clock', icon: 'schedule' },
    { value: 'money', label: 'Money', icon: 'money' },
    { value: 'egg_alt', label: 'Egg Alt', icon: 'egg_alt' },
    { value: 'restaurant', label: 'Restaurant', icon: 'restaurant' },
    { value: 'computer', label: 'Computer', icon: 'computer' }
];

export const CountryOptions = [
    { value: 'us', label: 'United States', subTitle: 'US' },
    { value: 'ca', label: 'Canada', subTitle: 'CA' },
    { value: 'mx', label: 'Mexico', subTitle: 'MX' },
    { value: 'uk', label: 'United Kingdom', subTitle: 'UK' },
    { value: 'de', label: 'Germany', subTitle: 'DE' },
    { value: 'fr', label: 'France', subTitle: 'FR' },
    { value: 'it', label: 'Italy', subTitle: 'IT' },
    { value: 'jp', label: 'Japan', subTitle: 'JP' },
    { value: 'cn', label: 'China', subTitle: 'CN' },
    { value: 'au', label: 'Australia', subTitle: 'AU' },
    { value: 'br', label: 'Brazil', subTitle: 'BR' },
    { value: 'in', label: 'India', subTitle: 'IN' },
    { value: 'ru', label: 'Russia', subTitle: 'RU' },
    { value: 'sa', label: 'Saudi Arabia', subTitle: 'SA' },
    { value: 'za', label: 'South Africa', subTitle: 'ZA' },
    { value: 'eg', label: 'Egypt', subTitle: 'EG' },
    { value: 'ng', label: 'Nigeria', subTitle: 'NG' },
    { value: 'id', label: 'Indonesia', subTitle: 'ID' },
    { value: 'tr', label: 'Turkey', subTitle: 'TR' },
    { value: 'kr', label: 'South Korea', subTitle: 'KR' },
    { value: 'ar', label: 'Argentina', subTitle: 'AR' },
    { value: 'at', label: 'Austria', subTitle: 'AT' },
    { value: 'be', label: 'Belgium', subTitle: 'BE' },
    { value: 'ch', label: 'Switzerland', subTitle: 'CH' },
    { value: 'dk', label: 'Denmark', subTitle: 'DK' },
    { value: 'fi', label: 'Finland', subTitle: 'FI' },
    { value: 'gr', label: 'Greece', subTitle: 'GR' },
    { value: 'hk', label: 'Hong Kong', subTitle: 'HK' },
    { value: 'ie', label: 'Ireland', subTitle: 'IE' },
    { value: 'il', label: 'Israel', subTitle: 'IL' },
    { value: 'my', label: 'Malaysia', subTitle: 'MY' },
    { value: 'nl', label: 'Netherlands', subTitle: 'NL' },
    { value: 'no', label: 'Norway', subTitle: 'NO' },
    { value: 'pl', label: 'Poland', subTitle: 'PL' },
    { value: 'pt', label: 'Portugal', subTitle: 'PT' },
    { value: 'se', label: 'Sweden', subTitle: 'SE' },
    { value: 'sg', label: 'Singapore', subTitle: 'SG' },
    { value: 'es', label: 'Spain', subTitle: 'ES' },
    { value: 'ph', label: 'Philippines', subTitle: 'PH' },
    { value: 'co', label: 'Colombia', subTitle: 'CO' },
    { value: 'th', label: 'Thailand', subTitle: 'TH' },
    { value: 'tw', label: 'Taiwan', subTitle: 'TW' },
    { value: 'vn', label: 'Vietnam', subTitle: 'VN' }
];

export const People = [
    { value: 'AB-E', label: 'Albert Einstein', subTitle: 'Physicist' },
    { value: 'IS-N', label: 'Isaac Newton', subTitle: 'Physicist' },
    { value: 'DA-D', label: 'Charles Darwin', subTitle: 'Naturalist' },
    { value: 'GA-G', label: 'Galileo Galilei', subTitle: 'Astronomer' },
    { value: 'DA-V', label: 'Leonardo da Vinci', subTitle: 'Artist' },
    { value: 'SH-H', label: 'Stephen Hawking', subTitle: 'Physicist' },
    { value: 'NE-I', label: 'Isaac Asimov', subTitle: 'Writer' },
    { value: 'NE-T', label: 'Nikola Tesla', subTitle: 'Inventor' },
    { value: 'NE-A', label: 'Neil Armstrong', subTitle: 'Astronaut' },
    { value: 'NE-S', label: 'Alberto Santos-Dumont', subTitle: 'Aviator' },
    { value: 'NE-L', label: 'Ada Lovelace', subTitle: 'Mathematician' },
    { value: 'NE-U', label: 'Alan Turing', subTitle: 'Computer Scientist' },
    { value: 'NE-B', label: 'Alexander Graham Bell', subTitle: 'Inventor' },
    { value: 'NE-E', label: 'Amelia Earhart', subTitle: 'Aviator' },
    { value: 'NE-R', label: 'Archimedes', subTitle: 'Mathematician' },
    { value: 'NE-O', label: 'Aristotle', subTitle: 'Philosopher' },
    { value: 'NE-F', label: 'Benjamin Franklin', subTitle: 'Inventor' },
    { value: 'NE-G', label: 'Bill Gates', subTitle: 'Entrepreneur' },
    { value: 'NE-J', label: 'Carl Sagan', subTitle: 'Astronomer' },
    { value: 'NE-K', label: 'Coco Chanel', subTitle: 'Fashion Designer' },
    { value: 'NE-Q', label: 'Confucius', subTitle: 'Philosopher' },
    { value: 'NE-M', label: 'Dmitri Mendeleev', subTitle: 'Chemist' },
    { value: 'NE-P', label: 'Edison', subTitle: 'Inventor' },
    { value: 'NE-Z', label: 'Einstein', subTitle: 'Physicist' },
    { value: 'NE-X', label: 'Emily Dickinson', subTitle: 'Poet' },
    { value: 'NE-W', label: 'Ernest Hemingway', subTitle: 'Writer' },
    { value: 'NE-C', label: 'Frida Kahlo', subTitle: 'Artist' },
    { value: 'NE-AB', label: 'George Washington', subTitle: 'Politician' },
    { value: 'NE-AC', label: 'Helen Keller', subTitle: 'Activist' },
    { value: 'NE-AD', label: 'Henry Ford', subTitle: 'Industrialist' },
    { value: 'NE-AF', label: 'Jane Austen', subTitle: 'Writer' },
    { value: 'NE-AG', label: 'Johannes Gutenberg', subTitle: 'Inventor' },
    { value: 'NE-AH', label: 'John F. Kennedy', subTitle: 'Politician' },
    { value: 'NE-AI', label: 'John Locke', subTitle: 'Philosopher' },
    { value: 'NE-AJ', label: 'John von Neumann', subTitle: 'Mathematician' },
    { value: 'NE-AL', label: 'Louis Pasteur', subTitle: 'Chemist' },
    { value: 'NE-AN', label: 'Marie Curie', subTitle: 'Chemist' },
    { value: 'NE-AO', label: 'Mark Twain', subTitle: 'Writer' },
    { value: 'NE-AP', label: 'Martin Luther King Jr.', subTitle: 'Activist' },
    { value: 'NE-AQ', label: 'Michael Jordan', subTitle: 'Athlete' },
    { value: 'NE-AR', label: 'Mozart', subTitle: 'Composer' },
    { value: 'NE-AS', label: 'Michael Jackson', subTitle: 'Musician' },
    { value: 'NE-AT', label: 'Michael Phelps', subTitle: 'Swimmer' },
    { value: 'NE-AU', label: 'Nelson Mandela', subTitle: 'Activist' },
    { value: 'NE-AV', label: 'Michael Faraday', subTitle: 'Physicist' },
    { value: 'NE-AW', label: 'Pablo Picasso', subTitle: 'Artist' },
    { value: 'NE-AX', label: 'Plato', subTitle: 'Philosopher' },
    { value: 'NE-AY', label: 'Pythagoras', subTitle: 'Mathematician' },
    { value: 'NE-AZ', label: 'Rosa Parks', subTitle: 'Activist' },
    { value: 'NE-BA', label: 'Sigmund Freud', subTitle: 'Psychologist' },
    { value: 'NE-BB', label: 'Michael Caine', subTitle: 'Actor' },
    { value: 'NE-BC', label: 'Steve Jobs', subTitle: 'Entrepreneur' },
    { value: 'NE-BD', label: 'Michaelangelo', subTitle: 'Artist' },
    { value: 'NE-BE', label: 'Vincent van Gogh', subTitle: 'Artist' },
    { value: 'NE-BF', label: 'Walt Disney', subTitle: 'Entrepreneur' },
    { value: 'NE-BG', label: 'William Shakespeare', subTitle: 'Writer' },
    { value: 'NE-BH', label: 'Winston Churchill', subTitle: 'Politician' },
    { value: 'NE-BI', label: 'Wright Brothers', subTitle: 'Aviators' },
    { value: 'NE-BJ', label: 'Yuri Gagarin', subTitle: 'Astronaut' },
    { value: 'NE-BK', label: 'Zhang Heng', subTitle: 'Inventor' },
    { value: 'NE-BQ', label: 'Aristotle', subTitle: 'Philosopher' },
    { value: 'NE-BR', label: 'Benjamin Franklin', subTitle: 'Inventor' },
    { value: 'NE-BS', label: 'Bill Gates', subTitle: 'Entrepreneur' },
    { value: 'NE-BT', label: 'Carl Sagan', subTitle: 'Astronomer' },
    { value: 'NE-BV', label: 'Confucius', subTitle: 'Philosopher' },
    { value: 'NE-BW', label: 'Dmitri Mendeleev', subTitle: 'Chemist' },
    { value: 'NE-BX', label: 'Edison', subTitle: 'Inventor' },
    { value: 'NE-BY', label: 'Einstein', subTitle: 'Physicist' },
    { value: 'NE-BZ', label: 'Elon Musk', subTitle: 'Entrepreneur' },
    { value: 'NE-CA', label: 'Emily Dickinson', subTitle: 'Poet' },
    { value: 'NE-CB', label: 'Ernest Hemingway', subTitle: 'Writer' },
    { value: 'NE-CC', label: 'Frida Kahlo', subTitle: 'Artist' },
    { value: 'NE-CE', label: 'George Washington', subTitle: 'Politician' },
    { value: 'NE-CF', label: 'Helen Keller', subTitle: 'Activist' },
    { value: 'NE-CG', label: 'Henry Ford', subTitle: 'Industrialist' },
    { value: 'NE-CH', label: 'Jane Austen', subTitle: 'Writer' },
    { value: 'NE-CI', label: 'Johannes Gutenberg', subTitle: 'Inventor' },
    { value: 'NE-CJ', label: 'John F. Kennedy', subTitle: 'Politician' },
    { value: 'NE-CK', label: 'John Locke', subTitle: 'Philosopher' },
    { value: 'NE-CL', label: 'John von Neumann', subTitle: 'Mathematician' },
    { value: 'NE-CM', label: 'Louis Pasteur', subTitle: 'Chemist' },
    { value: 'NE-CN', label: 'Mahatma Gandhi', subTitle: 'Activist' },
    { value: 'NE-CO', label: 'Marie Curie', subTitle: 'Chemist' },
    { value: 'NE-CP', label: 'Mark Twain', subTitle: 'Writer' },
    { value: 'NE-CQ', label: 'Martin Luther King Jr.', subTitle: 'Activist' },
    { value: 'NE-CS', label: 'Mozart', subTitle: 'Composer' },
    { value: 'NE-CT', label: 'Napoleon Bonaparte', subTitle: 'Military Leader' },
    { value: 'NE-CV', label: 'Pablo Picasso', subTitle: 'Artist' },
    { value: 'NE-CW', label: 'Plato', subTitle: 'Philosopher' },
    { value: 'NE-CX', label: 'Pythagoras', subTitle: 'Mathematician' },
    { value: 'NE-CY', label: 'Rosa Parks', subTitle: 'Activist' },
    { value: 'NE-CZ', label: 'Sigmund Freud', subTitle: 'Psychologist' },
    { value: 'NE-DB', label: 'Steve Jobs', subTitle: 'Entrepreneur' },
    { value: 'NE-DC', label: 'Thomas Edison', subTitle: 'Inventor' },
    { value: 'NE-DD', label: 'Vincent van Gogh', subTitle: 'Artist' },
    { value: 'NE-DE', label: 'Walt Disney', subTitle: 'Entrepreneur' },
    { value: 'NE-DG', label: 'Winston Churchill', subTitle: 'Politician' },
    { value: 'NE-DH', label: 'Wright Brothers', subTitle: 'Aviators' },
    { value: 'NE-DI', label: 'Yuri Gagarin', subTitle: 'Astronaut' },
    { value: 'NE-DJ', label: 'Zhang Heng', subTitle: 'Inventor' },
    { value: 'NE-ZB', label: 'Zhang Sanfeng', subTitle: 'Taoist Priest' },
    { value: 'NE-ZC', label: 'Zeno of Elea', subTitle: 'Philosopher' },
    { value: 'NE-ZD', label: 'Zinedine Zidane', subTitle: 'Footballer' },
    { value: 'NE-ZE', label: 'Zora Neale Hurston', subTitle: 'Writer' },
    { value: 'NE-ZF', label: 'Zubaida Tariq', subTitle: 'Chef' },
    { value: 'NE-ZG', label: 'Zygmunt Bauman', subTitle: 'Sociologist' },
    { value: 'NE-ZH', label: 'Zlatan Ibrahimovic', subTitle: 'Footballer' },
    { value: 'NE-ZI', label: 'Zhou Enlai', subTitle: 'Politician' },
    { value: 'NE-ZJ', label: 'Zig Ziglar', subTitle: 'Motivational Speaker' }
];

/**
 * Queries people based on the query string.
 * @param {string} query - The query string.
 * @returns {FieldOptionInterface[]} The queried people.
 */
export async function queryPeople(query) {
    if (!query) {
        return [...People].splice(0, 10);
    }
    return [...People].filter(
        option =>
            option.label.toLowerCase().includes(query.toLowerCase()) ||
            option.subTitle.toLowerCase().includes(query.toLowerCase())
    );
}

export const MusicGenres = [
    { value: 'ROCK', label: 'Rock' },
    { value: 'POP', label: 'Pop' },
    { value: 'HIPHOP', label: 'Hip Hop' },
    { value: 'JAZZ', label: 'Jazz' },
    { value: 'COUNTRY', label: 'Country' },
    { value: 'RNB', label: 'R&B' },
    { value: 'REGGAE', label: 'Reggae' },
    { value: 'BLUES', label: 'Blues' },
    { value: 'ELECTRONIC', label: 'Electronic' },
    { value: 'CLASSICAL', label: 'Classical' },
    { value: 'METAL', label: 'Metal' },
    { value: 'FOLK', label: 'Folk' },
    { value: 'INDIE', label: 'Indie' },
    { value: 'ALTERNATIVE', label: 'Alternative' },
    { value: 'LATIN', label: 'Latin' },
    { value: 'DANCE', label: 'Dance' },
    { value: 'SOUL', label: 'Soul' },
    { value: 'FUNK', label: 'Funk' },
    { value: 'DISCO', label: 'Disco' },
    { value: 'PUNK', label: 'Punk' },
    { value: 'COUNTRY', label: 'Country' },
    { value: 'RNB', label: 'R&B' },
    { value: 'REGGAE', label: 'Reggae' },
    { value: 'BLUES', label: 'Blues' }
];

export const MusicArtistsByGenre = {
    ROCK: [
        { value: 'ACDC', label: 'AC/DC' },
        { value: 'AEROSMITH', label: 'Aerosmith' },
        { value: 'BEATLES', label: 'The Beatles' },
        { value: 'BONJOVI', label: 'Bon Jovi' },
        { value: 'DOORS', label: 'The Doors' },
        { value: 'EAGLES', label: 'The Eagles' },
        { value: 'GUNS', label: "Guns N' Roses" },
        { value: 'LEDZEPPELIN', label: 'Led Zeppelin' },
        { value: 'METALLICA', label: 'Metallica' },
        { value: 'NIRVANA', label: 'Nirvana' },
        { value: 'PINKFLOYD', label: 'Pink Floyd' },
        { value: 'QUEEN', label: 'Queen' },
        { value: 'ROLLINGSTONES', label: 'The Rolling Stones' },
        { value: 'U2', label: 'U2' }
    ],
    POP: [
        { value: 'ABBA', label: 'ABBA' },
        { value: 'ADELE', label: 'Adele' },
        { value: 'BEYONCE', label: 'Beyoncé' },
        { value: 'BRITNEY', label: 'Britney Spears' },
        { value: 'COLDPLAY', label: 'Coldplay' },
        { value: 'ELTONJOHN', label: 'Elton John' },
        { value: 'JACKSON', label: 'Michael Jackson' },
        { value: 'MADONNA', label: 'Madonna' },
        { value: 'MAROON5', label: 'Maroon 5' },
        { value: 'PRINCE', label: 'Prince' },
        { value: 'RIHANNA', label: 'Rihanna' },
        { value: 'SHAKIRA', label: 'Shakira' }
    ],
    HIPHOP: [
        { value: '2PAC', label: '2Pac' },
        { value: 'BEASTIEBOYS', label: 'Beastie Bpys' },
        { value: 'DRAKE', label: 'Drake' },
        { value: 'EMINEM', label: 'Eminem' },
        { value: 'JAYZ', label: 'Jay-Z' },
        { value: 'KANYE', label: 'Kanye West' },
        { value: 'LILWAYNE', label: 'Lil Wayne' },
        { value: 'NAS', label: 'Nas' },
        { value: 'NOTORIOUSBIG', label: 'The Notorious B.I.G.' },
        { value: 'OUTKAST', label: 'OutKast' },
        { value: 'SNOOPDOGG', label: 'Snoop Dogg' },
        { value: 'TUPAC', label: 'Tupac' }
    ],
    COUNTRY: [
        { value: 'ALABAMA', label: 'Alabama' },
        { value: 'CARRIEUNDERWOOD', label: 'Carrie Underwood' },
        { value: 'DOLLYPARTON', label: 'Dolly Parton' },
        { value: 'GEORGESTRAIT', label: 'George Strait' },
        { value: 'JOHNNYCASH', label: 'Johnny Cash' },
        { value: 'KENNYCHESNEY', label: 'Kenny Chesney' },
        { value: 'LUKEBRYAN', label: 'Luke Bryan' },
        { value: 'SHANIATWAIN', label: 'Shania Twain' },
        { value: 'TIMMCGRAW', label: 'Tim McGraw' }
    ],
    RNB: [
        { value: 'ALICIAKEYS', label: 'Alicia Keys' },
        { value: 'BEYONCE', label: 'Beyoncé' },
        { value: 'CHRISBROWN', label: 'Chris Brown' },
        { value: 'DESTINYSCHILD', label: "Destiny's Child" },
        { value: 'JANETJACKSON', label: 'Janet Jackson' },
        { value: 'MARIAHCAREY', label: 'Mariah Carey' },
        { value: 'NEYO', label: 'Ne-Yo' },
        { value: 'RIHANNA', label: 'Rihanna' },
        { value: 'USHER', label: 'Usher' }
    ],
    REGGAE: [
        { value: 'BOB', label: 'Bob Marley' },
        { value: 'BUJU', label: 'Buju Banton' },
        { value: 'DAMIAN', label: 'Damian Marley' },
        { value: 'JIMMYCLIFF', label: 'Jimmy Cliff' },
        { value: 'PETER', label: 'Peter Tosh' },
        { value: 'SEANPAUL', label: 'Sean Paul' },
        { value: 'SHAGGY', label: 'Shaggy' },
        { value: 'TOOTS', label: 'Toots and The Maytals' },
        { value: 'ZIGGY', label: 'Ziggy Marley' }
    ],
    BLUES: [
        { value: 'BBKING', label: 'B.B. King' },
        { value: 'ERICCLAPTON', label: 'Eric Clapton' },
        { value: 'JOHNL', label: 'John Lee Hooker' },
        { value: 'MUDDYWATERS', label: 'Muddy Waters' },
        { value: 'ROBERTJ', label: 'Robert Johnson' },
        { value: 'STEVIERAY', label: 'Stevie Ray Vaughan' },
        { value: 'TBBONE', label: 'T-Bone Walker' },
        { value: 'WILLIE', label: 'Willie Dixon' }
    ],
    METAL: [
        { value: 'IRONMAIDEN', label: 'Iron Maiden' },
        { value: 'SLAYER', label: 'Slayer' },
        { value: 'MEGADETH', label: 'Megadeth' },
        { value: 'PANTERA', label: 'Pantera' },
        { value: 'JUDASPRIEST', label: 'Judas Priest' },
        { value: 'BLACKSABBATH', label: 'Black Sabbath' },
        { value: 'MOTORHEAD', label: 'Motörhead' },
        { value: 'SEPULTURA', label: 'Sepultura' },
        { value: 'DIMMU', label: 'Dimmu Borgir' },
        { value: 'SLIPKNOT', label: 'Slipknot' },
        { value: 'NIGHTWISH', label: 'Nightwish' },
        { value: 'ARCHENEMY', label: 'Arch Enemy' },
        { value: 'CHILDREN', label: 'Children of Bodom' },
        { value: 'SYSTEM', label: 'System of a Down' },
        { value: 'INFLAMES', label: 'In Flames' },
        { value: 'KILLSWITCH', label: 'Killswitch Engage' },
        { value: 'LAMB', label: 'Lamb of God' },
        { value: 'OPETH', label: 'Opeth' },
        { value: 'TRIVIUM', label: 'Trivium' },
        { value: 'AVENGED', label: 'Avenged Sevenfold' }
    ],
    FOLK: [
        { value: 'BOB', label: 'Bob Dylan' },
        { value: 'WOODY', label: 'Woody Guthrie' },
        { value: 'JOHNNY', label: 'Johnny Cash' },
        { value: 'SIMON', label: 'Paul Simon' },
        { value: 'JONIM', label: 'Joni Mitchell' },
        { value: 'NEILY', label: 'Neil Young' },
        { value: 'PETE', label: 'Pete Seeger' },
        { value: 'GORDON', label: 'Gordon Lightfoot' },
        { value: 'ARLO', label: 'Arlo Guthrie' },
        { value: 'DONOVAN', label: 'Donovan' },
        { value: 'JAMES', label: 'James Taylor' },
        { value: 'LEONARD', label: 'Leonard Cohen' },
        { value: 'JOAN', label: 'Joan Baez' },
        { value: 'BUFFY', label: 'Buffy Sainte-Marie' },
        { value: 'RICHIE', label: 'Richie Havens' },
        { value: 'JUDY', label: 'Judy Collins' },
        { value: 'BILLY', label: 'Billy Bragg' },
        { value: 'ANNE', label: 'Anne Briggs' },
        { value: 'BERT', label: 'Bert Jansch' },
        { value: 'SANDY', label: 'Sandy Denny' }
    ],
    INDIE: [
        { value: 'ARCTIC', label: 'Arctic Monkeys' },
        { value: 'VAMPIRE', label: 'Vampire Weekend' },
        { value: 'STROKES', label: 'The Strokes' },
        { value: 'PIXIES', label: 'Pixies' },
        { value: 'RADIOHEAD', label: 'Radiohead' },
        { value: 'INTERPOL', label: 'Interpol' },
        { value: 'FOALS', label: 'Foals' },
        { value: 'TAME', label: 'Tame Impala' },
        { value: 'BEACH', label: 'Beach House' },
        { value: 'ARCADE', label: 'Arcade Fire' },
        { value: 'BLOC', label: 'Bloc Party' },
        { value: 'MODEST', label: 'Modest Mouse' },
        { value: 'DEATH', label: 'Death Cab for Cutie' },
        { value: 'FRANZ', label: 'Franz Ferdinand' },
        { value: 'MUMFORD', label: 'Mumford & Sons' },
        { value: 'WOMBATS', label: 'The Wombats' },
        { value: 'VACCINES', label: 'The Vaccines' },
        { value: 'KOOKS', label: 'The Kooks' },
        { value: 'LIBERTINES', label: 'The Libertines' },
        { value: 'KILLERS', label: 'The Killers' }
    ],
    ALTERNATIVE: [
        { value: 'NIRVANA', label: 'Nirvana' },
        { value: 'RADIOHEAD', label: 'Radiohead' },
        { value: 'PEARL', label: 'Pearl Jam' },
        { value: 'SMASHING', label: 'Smashing Pumpkins' },
        { value: 'PIXIES', label: 'Pixies' },
        { value: 'OASIS', label: 'Oasis' },
        { value: 'BLUR', label: 'Blur' },
        { value: 'SOUNDGARDEN', label: 'Soundgarden' },
        { value: 'WEEZER', label: 'Weezer' },
        { value: 'GREEN', label: 'Green Day' },
        { value: 'RAGE', label: 'Rage Against the Machine' },
        { value: 'STONE', label: 'Stone Temple Pilots' },
        { value: 'ALICE', label: 'Alice in Chains' },
        { value: 'RED', label: 'Red Hot Chili Peppers' },
        { value: 'CURE', label: 'The Cure' },
        { value: 'DEPECHE', label: 'Depeche Mode' },
        { value: 'BLONDIE', label: 'Blondie' },
        { value: 'RAMONES', label: 'Ramones' },
        { value: 'WHITE', label: 'The White Stripes' },
        { value: 'COLDPLAY', label: 'Coldplay' }
    ],
    LATIN: [
        { value: 'SHAKIRA', label: 'Shakira' },
        { value: 'JUANES', label: 'Juanes' },
        { value: 'ENRIQUE', label: 'Enrique Iglesias' },
        { value: 'MALUMA', label: 'Maluma' },
        { value: 'JLO', label: 'Jennifer Lopez' },
        { value: 'RICKY', label: 'Ricky Martin' },
        { value: 'THALIA', label: 'Thalía' },
        { value: 'MANA', label: 'Maná' },
        { value: 'JULIO', label: 'Julio Iglesias' },
        { value: 'GLORIA', label: 'Gloria Estefan' },
        { value: 'CARLOS', label: 'Carlos Santana' },
        { value: 'VICENTE', label: 'Vicente Fernández' },
        { value: 'JUAN', label: 'Juan Gabriel' },
        { value: 'ALEJANDRO', label: 'Alejandro Sanz' },
        { value: 'LUI', label: 'Luis Miguel' },
        { value: 'THALIA', label: 'Thalía' },
        { value: 'MANA', label: 'Maná' },
        { value: 'JULIO', label: 'Julio Iglesias' },
        { value: 'GLORIA', label: 'Gloria Estefan' },
        { value: 'CARLOS', label: 'Carlos Santana' }
    ],
    DANCE: [
        { value: 'DAFT', label: 'Daft Punk' },
        { value: 'AVICII', label: 'Avicii' },
        { value: 'CALVIN', label: 'Calvin Harris' },
        { value: 'DAVID', label: 'David Guetta' },
        { value: 'TIESTO', label: 'Tiësto' },
        { value: 'SWEDISH', label: 'Swedish House Mafia' },
        { value: 'SKRILLEX', label: 'Skrillex' },
        { value: 'DEADMAU5', label: 'Deadmau5' },
        { value: 'MARTIN', label: 'Martin Garrix' },
        { value: 'ZEDD', label: 'Zedd' },
        { value: 'AFROJACK', label: 'Afrojack' },
        { value: 'STEVE', label: 'Steve Aoki' },
        { value: 'DIPLO', label: 'Diplo' },
        { value: 'KASKADE', label: 'Kaskade' },
        { value: 'ARMIN', label: 'Armin van Buuren' },
        { value: 'SKRILLEX', label: 'Skrillex' },
        { value: 'DEADMAU5', label: 'Deadmau5' },
        { value: 'MARTIN', label: 'Martin Garrix' },
        { value: 'ZEDD', label: 'Zedd' },
        { value: 'AFROJACK', label: 'Afrojack' }
    ],
    SOUL: [
        { value: 'ARETHA', label: 'Aretha Franklin' },
        { value: 'OTIS', label: 'Otis Redding' },
        { value: 'STEVIE', label: 'Stevie Wonder' },
        { value: 'RAY', label: 'Ray Charles' },
        { value: 'SAM', label: 'Sam Cooke' },
        { value: 'AL', label: 'Al Green' },
        { value: 'TINA', label: 'Tina Turner' },
        { value: 'MARVIN', label: 'Marvin Gaye' },
        { value: 'AMY', label: 'Amy Winehouse' },
        { value: 'ERYKAH', label: 'Erykah Badu' },
        { value: 'LAURYN', label: 'Lauryn Hill' },
        { value: 'BILL', label: 'Bill Withers' },
        { value: 'OTIS', label: 'Otis Redding' },
        { value: 'STEVIE', label: 'Stevie Wonder' },
        { value: 'RAY', label: 'Ray Charles' },
        { value: 'SAM', label: 'Sam Cooke' },
        { value: 'AL', label: 'Al Green' },
        { value: 'TINA', label: 'Tina Turner' }
    ],
    FUNK: [
        { value: 'JAMESB', label: 'James Brown' },
        { value: 'GEORGE', label: 'George Clinton' },
        { value: 'SLY', label: 'Sly and The Family Stone' },
        { value: 'PARLIAMENT', label: 'Parliament-Funkadelic' },
        { value: 'ISAAC', label: 'Isaac Hayes' },
        { value: 'CURTIS', label: 'Curtis Mayfield' },
        { value: 'PRINCE', label: 'Prince' },
        { value: 'CHIC', label: 'Chic' },
        { value: 'KOOL', label: 'Kool & The Gang' },
        { value: 'EARTH', label: 'Earth, Wind & Fire' },
        { value: 'JACKSON', label: 'The Jackson 5' },
        { value: 'COMMODORES', label: 'The Commodores' },
        { value: 'TOWER', label: 'Tower of Power' },
        { value: 'WAR', label: 'War' },
        { value: 'BARRY', label: 'Barry White' },
        { value: 'JAMESB', label: 'James Brown' },
        { value: 'GEORGE', label: 'George Clinton' },
        { value: 'SLY', label: 'Sly and The Family Stone' },
        { value: 'PARLIAMENT', label: 'Parliament-Funkadelic' },
        { value: 'ISAAC', label: 'Isaac Hayes' }
    ],
    DISCO: [
        { value: 'BEE', label: 'Bee Gees' },
        { value: 'DONNA', label: 'Donna Summer' },
        { value: 'KC', label: 'KC and The Sunshine Band' },
        { value: 'GLORIA', label: 'Gloria Gaynor' },
        { value: 'CHIC', label: 'Chic' },
        { value: 'ABBA', label: 'ABBA' },
        { value: 'VILLAGE', label: 'Village People' },
        { value: 'BARRY', label: 'Barry White' },
        { value: 'TAVARES', label: 'Tavares' },
        { value: 'SISTER', label: 'Sister Sledge' },
        { value: 'BONEY', label: 'Boney M.' },
        { value: 'EARTH', label: 'Earth, Wind & Fire' },
        { value: 'JACKSON', label: 'The Jackson 5' },
        { value: 'COMMODORES', label: 'The Commodores' },
        { value: 'TOWER', label: 'Tower of Power' },
        { value: 'WAR', label: 'War' },
        { value: 'BEE', label: 'Bee Gees' },
        { value: 'DONNA', label: 'Donna Summer' },
        { value: 'KC', label: 'KC and The Sunshine Band' },
        { value: 'GLORIA', label: 'Gloria Gaynor' }
    ],
    PUNK: [
        { value: 'RAMONES', label: 'Ramones' },
        { value: 'SEX', label: 'Sex Pistols' },
        { value: 'CLASH', label: 'The Clash' },
        { value: 'DEAD', label: 'Dead Kennedys' },
        { value: 'BLACK', label: 'Black Flag' },
        { value: 'MISFITS', label: 'Misfits' },
        { value: 'BAD', label: 'Bad Religion' },
        { value: 'RANCID', label: 'Rancid' },
        { value: 'GREEN', label: 'Green Day' },
        { value: 'OFFSPRING', label: 'The Offspring' },
        { value: 'BUZZCOCKS', label: 'Buzzcocks' },
        { value: 'X', label: 'X' },
        { value: 'DAMNED', label: 'The Damned' },
        { value: 'CIRCLE', label: 'Circle Jerks' },
        { value: 'MINOR', label: 'Minor Threat' },
        { value: 'BAD', label: 'Bad Religion' },
        { value: 'RANCID', label: 'Rancid' },
        { value: 'GREEN', label: 'Green Day' },
        { value: 'OFFSPRING', label: 'The Offspring' },
        { value: 'BUZZCOCKS', label: 'Buzzcocks' }
    ]
};
