export const IconOptions = [
    { value: 'grocery', label: 'Grocery', icon: 'grocery' },
    { value: 'nutrition', label: 'Nutrition', icon: 'nutrition' },
    { value: 'person', label: 'Person', icon: 'person' },
    { value: 'local_shipping', label: 'Local Shipping', icon: 'local_shipping' },
    { value: 'home', label: 'Home', icon: 'home' },
    { value: 'music_note', label: 'Music Note', icon: 'music_note' },
    { value: 'book', label: 'Book', icon: 'book' },
    { value: 'camera', label: 'Camera', icon: 'camera' },
    { value: 'globe', label: 'Globe', icon: 'globe' },
    { value: 'favorite', label: 'Favorite', icon: 'favorite' },
    { value: 'star', label: 'Star', icon: 'star' },
    { value: 'smart_toy', label: 'Smart Toy', icon: 'smart_toy' },
    { value: 'movie', label: 'Movie', icon: 'movie' },
    { value: 'phone', label: 'Phone', icon: 'phone' },
    { value: 'mail', label: 'Mail', icon: 'mail' },
    { value: 'clock', label: 'Clock', icon: 'schedule' },
    { value: 'money', label: 'Money', icon: 'money' },
    { value: 'egg_alt', label: 'Egg Alt', icon: 'egg_alt' },
    { value: 'restaurant', label: 'Restaurant', icon: 'restaurant' },
    { value: 'computer', label: 'Computer', icon: 'computer' }
];

export const CountryOptions = [
    { value: 'us', label: 'United States' },
    { value: 'ca', label: 'Canada' },
    { value: 'mx', label: 'Mexico' },
    { value: 'uk', label: 'United Kingdom' },
    { value: 'de', label: 'Germany' },
    { value: 'fr', label: 'France' },
    { value: 'es', label: 'Spain' },
    { value: 'it', label: 'Italy' },
    { value: 'jp', label: 'Japan' },
    { value: 'cn', label: 'China' },
    { value: 'au', label: 'Australia' },
    { value: 'br', label: 'Brazil' },
    { value: 'in', label: 'India' },
    { value: 'ru', label: 'Russia' },
    { value: 'sa', label: 'Saudi Arabia' },
    { value: 'za', label: 'South Africa' },
    { value: 'eg', label: 'Egypt' },
    { value: 'ng', label: 'Nigeria' },
    { value: 'id', label: 'Indonesia' },
    { value: 'tr', label: 'Turkey' },
    { value: 'kr', label: 'South Korea' },
    { value: 'ar', label: 'Argentina' },
    { value: 'at', label: 'Austria' },
    { value: 'be', label: 'Belgium' },
    { value: 'ch', label: 'Switzerland' },
    { value: 'dk', label: 'Denmark' },
    { value: 'fi', label: 'Finland' },
    { value: 'gr', label: 'Greece' },
    { value: 'hk', label: 'Hong Kong' },
    { value: 'ie', label: 'Ireland' },
    { value: 'il', label: 'Israel' },
    { value: 'my', label: 'Malaysia' },
    { value: 'nl', label: 'Netherlands' },
    { value: 'no', label: 'Norway' },
    { value: 'pl', label: 'Poland' },
    { value: 'pt', label: 'Portugal' },
    { value: 'se', label: 'Sweden' },
    { value: 'sg', label: 'Singapore' },
    { value: 'th', label: 'Thailand' },
    { value: 'tw', label: 'Taiwan' },
    { value: 'vn', label: 'Vietnam' }
];
